feat: add codecov
Signed-off-by: Vishal Choudhary <vishal.choudhary@nirmata.com>

diff --git a/.github/workflows/go-test.yaml b/.github/workflows/go-test.yaml
--- a/.github/workflows/go-test.yaml
+++ b/.github/workflows/go-test.yaml
@@ -1,4 +1,8 @@
-name: test
+# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
+
+name: Tests
+
+permissions: {}
 
 on:
   push:
@@ -9,22 +13,37 @@ on:
       - 'main'
       - 'release*'
 
-jobs:
-  build:
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
+jobs:
+  unit-tests:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: '1.22.x'
-      - name: Install dependencies
-        run: go get ./...
-      - name: Test with Go
-        run: go test ./... -json > test-results.json
-      - name: Upload Go test results
-        uses: actions/upload-artifact@v4
-        with:
-          name: Go-test-results
-          path: test-results.json
+    - name: Checkout
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
+      with:
+        go-version-file: go.mod
+        cache-dependency-path: go.sum
+    - name: Run tests
+      run: |
+        set -e
+        make tests
+    - name: Upload Report to Codecov
+      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
+      with:
+        files: ./coverage.out
+        fail_ci_if_error: true
+        verbose: true
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+
+  required:
+    needs:
+    - unit-tests
+    runs-on: ubuntu-latest
+    steps:
+    - run: echo "Required jobs success!"
+
